name: Build & Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
   
env:
  GitHubName: pitchblackrecoveryproject
  GitHubMail: ${{ secrets.GitHubMail }}

  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

  # Image name and tag. MUST be lowercase
  IMAGE_NAME: docker
  IMAGE_TAG: latest

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GitHubName
          password: $GH_BOT_TOKEN
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${GitHubName}/${IMAGE_NAME}:${{IMAGE_TAG}
