name: Build & Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
   
env:
  GitHubName: pitchblackrecoveryproject
  GitHubMail: ${{ secrets.GitHubMail }}
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  
  IMAGE_NAME: ubuntu
  IMAGE_TAG: latest

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Logging in to Docker
        run: |
          echo $GH_BOT_TOKEN | docker login ghcr.io -u $GitHubName --password-stdin
      - name: Building the Image
        run: |
          docker build -t ghcr.io/${GitHubName}/${IMAGE_NAME}:${IMAGE_TAG} .
          echo "Build Completed Successfully!"
      - name: Pushing the Image
        run: |
          docker push ghcr.io/${GitHubName}/${IMAGE_NAME}:${IMAGE_TAG}
